CREATE DATABASE  IF NOT EXISTS `recycling`;

USE `recycling`

CREATE TABLE `garbage` IF NOT EXISTS (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT '',
  `kind` enum('RECYCLABLE','HARMFUL','WET','DRY') NOT NULL DEFAULT 'RECYCLABLE',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14751 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;